package com.torben.template;

public enum ConfigMessage {

    WELCOME_MESSAGE,
    LANG_FILE_LOAD_ERROR,
    DATABASE_CONNECTION_STATUS,
    RUNNABLE_MESSAGE,
    CUSTOM_BOOK_GIVEN,
    CUSTOM_BANNER_GIVEN,
    CUSTOM_DYED_ARMOR_GIVEN,
    PLAYER_HEAD_GIVEN,
    CUSTOM_SKULL_GIVEN
}
